In [2]:
import torch
from torch import nn

In [3]:
net = nn.Sequential(nn.Linear(4, 3), nn.ReLU(), nn.Linear(3, 1))
print(net)

Sequential(
  (0): Linear(in_features=4, out_features=3, bias=True)
  (1): ReLU()
  (2): Linear(in_features=3, out_features=1, bias=True)
)


In [4]:
# 初始化权重和偏置
for name, param in net[0].named_parameters():
    print(name, param.shape)
    print(name, param)
    if "weight" in name:
        torch.nn.init.normal_(param, mean=0, std=0.01)
    if "bias" in name:
        torch.nn.init.constant_(param, val=0)
    print(name, param)

weight torch.Size([3, 4])
weight Parameter containing:
tensor([[ 0.4904,  0.3275,  0.4002,  0.1335],
        [ 0.1689, -0.1981,  0.0313,  0.4232],
        [-0.4650, -0.2535, -0.1201,  0.2069]], requires_grad=True)
weight Parameter containing:
tensor([[ 0.0030, -0.0119,  0.0025,  0.0193],
        [ 0.0172,  0.0021, -0.0174, -0.0045],
        [-0.0056,  0.0121,  0.0061, -0.0029]], requires_grad=True)
bias torch.Size([3])
bias Parameter containing:
tensor([-0.3915,  0.2877, -0.2407], requires_grad=True)
bias Parameter containing:
tensor([0., 0., 0.], requires_grad=True)


In [5]:
filepath = './test.pth'
torch.save(net.state_dict, filepath)